### ISSUE TITLE
Jupyter Note for R --keep getting 'kernel have died' error 

### ISSUE THREAD

**Issue by FCHLuk** [Microsoft/AzureNotebooks#593]
I keep getting the following error message when it tries to execute the last line in the code block that follows. This is just the bike rental regression exercise in  Microsoft -  DAT203.2x, Principles of Machine Learning course. It used to work several months ago. If I reduce the number of rows to 100, then it ran. Is there any way I could configure it to use more memory if memory is an issue ?

-----------------------------------------------------------------
"Kernel Restarting
The kernel appears to have died. It will restart automatically."
library("AzureML")
ws <- workspace('ae24c20fadf145f58c9547b6ee5591a9','bb03457a9f5b49e9b422d0ac6cc08e7d')
dat <- download.intermediate.dataset(
  ws,
  experiment = "ae24c20fadf145f58c9547b6ee5591a9.f-id.fd74fff4f5d349ff8c0e005934486adb",
  node_id = "1356109b-5b3a-4e38-a4db-9f616c6dbb7e-3409",
  port_name = "Results dataset",
  data_type_id = "GenericCSV"
)

numCols <- c("temp", "hum", "windspeed", "hr")
bike.scatter <- function(df, cols){
require(ggplot2)
for(col in cols){
p1 <- ggplot(df, aes_string(x = col, y = "cnt")) +
geom_point(aes(alpha = 0.001, color = "blue")) +
geom_smooth(method = "loess") +
ggtitle(paste('Count of bikes rented vs. ', col)) +
theme(text = element_text(size=16))
print(p1)
}
}

bike.scatter(dat, numCols)

**Comment by FCHLuk** [comment]
Help !

**Comment by rachelgshaffer** [comment]
Apologies that you are experiencing this issue and for the delay in responding. Can you provide a link to your notebook (and make sure the project is public) and then we can take a closer look. Thanks for using Azure Notebooks!

**Comment by FCHLuk** [comment]
Hi Rachel, Thank you for your response. I don't know how to make it public. But here is the link.
https://notebooks.azure.com/n/mvcvc9wcbatlaq/notebooks/Bike%20Rental%20Visualization.ipynb#
This is just a notebook from Azure ML. I tried to download it. But it didn't download.

Now I am getting different result. I got the message below when I tried to plot with the following code.

numCols <- c("temp", "hum", "windspeed", "hr")
bike.scatter <- function(df, cols){
require(ggplot2)
for(col in cols){
p1 <- ggplot(df, aes_string(x = col, y = "cnt")) +
geom_point(aes(alpha = 0.001, color = "blue")) +
geom_smooth(method = "loess") +
ggtitle(paste('Count of bikes rented vs. ', col)) +
theme(text = element_text(size=16))
print(p1)
}
---------------------------
Warning message:
“Computation failed in `stat_smooth()`:
'Calloc' could not allocate memory (453222645 of 8 bytes)”Warning message:
“Computation failed in `stat_smooth()`:
'Calloc' could not allocate memory (453222645 of 8 bytes)”
---------------------------------

**Comment by rachelgshaffer** [comment]
We recently deployed a fix that should resolve this issue. Please reactivate if you are still having trouble getting into an R kernel. Thanks for using Azure Notebooks!

**Comment by FCHLuk** [comment]
Hi Rachel, Unfortunately, it still does not work. I am still getting "Kernel appears to have died..." message. It looks like the original error is still there. Please see attached screen shot.
![bikeregressionbug](https://user-images.githubusercontent.com/42013060/52687330-42e31b80-2f06-11e9-8c0f-4459392001ec.png)

**Comment by FCHLuk** [comment]
Hi Rachel,

I am still getting the same error. It doesn't look like anything has 
changed.

Please see screenshot that I uploaded to GitHub.

Thanks,

Fred
